# constants from pump
PUMP_INERTIA_THRESHOLD_PERCENT = 15

# constants from processValue
DEFAULT_OPERATOR_VFD_SETPOINT = 550
DEFAULT_TANK_LEVEL = 850
DEFAULT_VFD_SETPOINT = 550
PSI_SCALE_MULTIPLIER = 10

# constants from processSim
DEADBAND = 10
DELTA_TIME_S = 0.5
FLOW_GAIN = 5
MAX_CHEM_GPM_AT_MAX_FLOW = 0.01875
MAX_FLOW_GPM = 1550
MIN_PROCESS_VALUE = 0
MINUTES_IN_DAY = 1440
VFD_ERROR_GAIN_DIVISOR = 5
VFD_MAX_PERCENT = 100
VFD_MIN_PERCENT = 0
VFD_SAFETY_MARGIN_PERCENT = 2

# constants for main
COIL_COUNT = 50
FC_COILS = 1
FC_HOLDING_REGISTERS = 3
HOLDING_REGISTER_COUNT = 50
MODBUS_HOST = "127.0.0.1"
MODBUS_PORT = 5020
SCAN_CYCLE_TIME_S: float = 1.0

# Alarm thresholds
HIGH_HIGH_PSI_THRESHOLD = 800
HIGH_PSI_THRESHOLD = 700
LOW_FLOW_THRESHOLD_GPM = 300
LOW_LOW_PSI_THRESHOLD = 200
LOW_PSI_THRESHOLD = 400
PUMP_LOW_FLOW_TRIP_DELAY_S = 40
TANK_LEVEL_HIGH_HIGH_THRESHOLD = 950
TANK_LEVEL_HIGH_THRESHOLD = 900
TANK_LEVEL_LOW_LOW_THRESHOLD = 100
TANK_LEVEL_LOW_THRESHOLD = 250

# Holding Register Map (processValues) - keep numeric order
HR_TANK_LEVEL: int = 0
HR_ACTUAL_PSI: int = 1
HR_FLOW_GPM: int = 2
HR_CHEMICAL_DOSE_GPD: int = 3
HR_VFD_SPEED_PERCENT: int = 4
HR_SYSTEM_REQUIRED_PSI: int = 5
HR_TOTAL_HEAD_PSI: int = 6
HR_VFD_SETPOINT: int = 7

# Coil Map (commands / alarms) - keep numeric order
COIL_PUMP_CMD = 0
COIL_PUMP_RUNNING = 1
COIL_PUMP_FAULT = 2
COIL_CHLORINE_INJ_PUMP = 3
COIL_PUMP_RUN_PERMIT = 5
COIL_TANK_LEVEL_LOW_ALARM = 11
COIL_TANK_LEVEL_LOW_LOW_ALARM = 12
COIL_TANK_LEVEL_HIGH_ALARM = 13
COIL_TANK_LEVEL_HIGH_HIGH_ALARM = 14
COIL_LOW_PSI_ALARM = 15
COIL_LOW_LOW_PSI_ALARM = 16
COIL_HIGH_PSI_ALARM = 17
COIL_HIGH_HIGH_PSI_ALARM = 18
COIL_PUMP_FAULT_UNLATCH = 19